/**
 * Centralized dummy data for local development and testing
 * Used as fallback when APIs are unavailable
 */

import type { Class, Student, Attendance, Assessment, SubjectGrade } from "./types"

export const DUMMY_CLASSES: Class[] = [
  {
    _id: "class1",
    className: "Grade 1 - A",
    level: "1",
    section: "A",
    academicYear: "2024-2025",
    capacity: 40,
    currentEnrollment: 25,
    subjects: ["Mathematics", "English", "Science", "Social Studies"],
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    _id: "class2",
    className: "Grade 2 - A",
    level: "2",
    section: "A",
    academicYear: "2024-2025",
    capacity: 40,
    currentEnrollment: 28,
    subjects: ["Mathematics", "English", "Science", "Social Studies", "History"],
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    _id: "class3",
    className: "Grade 3 - A",
    level: "3",
    section: "A",
    academicYear: "2024-2025",
    capacity: 40,
    currentEnrollment: 30,
    subjects: ["Mathematics", "English", "Science", "Social Studies", "Geography"],
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
]

export const DUMMY_STUDENTS: Student[] = [
  {
    _id: "stu1",
    studentId: "S001",
    firstName: "Alice",
    lastName: "Johnson",
    dateOfBirth: new Date("2015-03-15"),
    gender: "female",
    classId: "class1",
    guardianName: "Mary Johnson",
    guardianPhone: "+233-501-234-567",
    guardianEmail: "mary.johnson@example.com",
    address: "123 Maple Street, Accra",
    admissionDate: new Date("2023-09-01"),
    status: "active",
    createdAt: new Date("2023-09-01"),
    updatedAt: new Date("2024-12-19"),
  },
  {
    _id: "stu2",
    studentId: "S002",
    firstName: "Bob",
    lastName: "Smith",
    dateOfBirth: new Date("2015-07-22"),
    gender: "male",
    classId: "class1",
    guardianName: "John Smith",
    guardianPhone: "+233-502-345-678",
    guardianEmail: "john.smith@example.com",
    address: "456 Oak Avenue, Accra",
    admissionDate: new Date("2023-09-01"),
    status: "active",
    createdAt: new Date("2023-09-01"),
    updatedAt: new Date("2024-12-19"),
  },
  {
    _id: "stu3",
    studentId: "S003",
    firstName: "Chloe",
    lastName: "Williams",
    dateOfBirth: new Date("2015-11-30"),
    gender: "female",
    classId: "class1",
    guardianName: "Sarah Williams",
    guardianPhone: "+233-503-456-789",
    guardianEmail: "sarah.williams@example.com",
    address: "789 Pine Road, Tema",
    admissionDate: new Date("2023-09-01"),
    status: "active",
    createdAt: new Date("2023-09-01"),
    updatedAt: new Date("2024-12-19"),
  },
  {
    _id: "stu4",
    studentId: "S004",
    firstName: "David",
    lastName: "Brown",
    dateOfBirth: new Date("2014-05-18"),
    gender: "male",
    classId: "class2",
    guardianName: "Michael Brown",
    guardianPhone: "+233-504-567-890",
    guardianEmail: "michael.brown@example.com",
    address: "321 Elm Street, Kumasi",
    admissionDate: new Date("2023-09-01"),
    status: "active",
    createdAt: new Date("2023-09-01"),
    updatedAt: new Date("2024-12-19"),
  },
  {
    _id: "stu5",
    studentId: "S005",
    firstName: "Emma",
    lastName: "Davis",
    dateOfBirth: new Date("2014-09-25"),
    gender: "female",
    classId: "class2",
    guardianName: "Jennifer Davis",
    guardianPhone: "+233-505-678-901",
    guardianEmail: "jennifer.davis@example.com",
    address: "654 Birch Lane, Takoradi",
    admissionDate: new Date("2023-09-01"),
    status: "active",
    createdAt: new Date("2023-09-01"),
    updatedAt: new Date("2024-12-19"),
  },
]

export const DUMMY_ATTENDANCE_RECORDS: Attendance[] = [
  {
    _id: "att1",
    studentId: "stu1",
    classId: "class1",
    date: new Date("2024-12-19"),
    status: "present",
    markedBy: "teacher1",
    createdAt: new Date("2024-12-19"),
  },
  {
    _id: "att2",
    studentId: "stu2",
    classId: "class1",
    date: new Date("2024-12-19"),
    status: "late",
    notes: "Arrived 15 minutes late",
    markedBy: "teacher1",
    createdAt: new Date("2024-12-19"),
  },
  {
    _id: "att3",
    studentId: "stu3",
    classId: "class1",
    date: new Date("2024-12-19"),
    status: "absent",
    notes: "Medical appointment",
    markedBy: "teacher1",
    createdAt: new Date("2024-12-19"),
  },
  {
    _id: "att4",
    studentId: "stu4",
    classId: "class2",
    date: new Date("2024-12-19"),
    status: "present",
    markedBy: "teacher2",
    createdAt: new Date("2024-12-19"),
  },
]

export const DUMMY_ASSESSMENTS: Assessment[] = [
  {
    _id: "assess1",
    title: "Mathematics Quiz 1",
    description: "Basic arithmetic and problem-solving",
    classId: "class1",
    subjectCode: "MATH101",
    assessmentType: "quiz",
    totalMarks: 20,
    weight: 10,
    dueDate: new Date("2024-12-25"),
    createdBy: "teacher1",
    createdAt: new Date("2024-12-10"),
    updatedAt: new Date("2024-12-10"),
  },
  {
    _id: "assess2",
    title: "English Mid-term Exam",
    description: "Reading comprehension and writing",
    classId: "class1",
    subjectCode: "ENG101",
    assessmentType: "midterm",
    totalMarks: 100,
    weight: 30,
    dueDate: new Date("2024-12-30"),
    createdBy: "teacher1",
    createdAt: new Date("2024-12-01"),
    updatedAt: new Date("2024-12-01"),
  },
  {
    _id: "assess3",
    title: "Science Project",
    description: "Experimental project on renewable energy",
    classId: "class2",
    subjectCode: "SCI101",
    assessmentType: "project",
    totalMarks: 50,
    weight: 25,
    dueDate: new Date("2025-01-15"),
    createdBy: "teacher2",
    createdAt: new Date("2024-11-15"),
    updatedAt: new Date("2024-11-15"),
  },
]

export const DUMMY_SUBJECT_GRADES: SubjectGrade[] = [
  {
    subjectCode: "MATH101",
    subjectName: "Mathematics",
    totalMarks: 100,
    obtainedMarks: 88,
    percentage: 88,
    grade: "A",
    remarks: "Excellent performance",
  },
  {
    subjectCode: "ENG101",
    subjectName: "English",
    totalMarks: 100,
    obtainedMarks: 76,
    percentage: 76,
    grade: "B",
    remarks: "Very Good",
  },
  {
    subjectCode: "SCI101",
    subjectName: "Science",
    totalMarks: 100,
    obtainedMarks: 82,
    percentage: 82,
    grade: "A",
    remarks: "Very Good",
  },
  {
    subjectCode: "SS101",
    subjectName: "Social Studies",
    totalMarks: 100,
    obtainedMarks: 79,
    percentage: 79,
    grade: "B",
    remarks: "Good",
  },
]

export const DUMMY_REPORT_DATA = {
  student: {
    _id: "stu1",
    studentId: "S001",
    name: "Alice Johnson",
  },
  subjectGrades: DUMMY_SUBJECT_GRADES,
  overall: {
    totalMarks: 400,
    obtainedMarks: 325,
    percentage: 81.25,
    grade: "A",
    remarks: "Excellent performance with consistent grades across all subjects",
  },
}

export const DUMMY_TIMETABLE = {
  Grade1: {
    Monday: [
      { time: "08:00 - 09:00", subject: "Mathematics", teacher: "Mrs. Abena Osei", room: "1A" },
      { time: "09:00 - 10:00", subject: "English", teacher: "Mr. Kofi Mensah", room: "1A" },
      { time: "10:15 - 11:15", subject: "Science", teacher: "Ms. Ama Boateng", room: "Lab 1" },
      { time: "11:15 - 12:15", subject: "Social Studies", teacher: "Mr. Kwame Asante", room: "1A" },
    ],
    Tuesday: [
      { time: "08:00 - 09:00", subject: "English", teacher: "Mr. Kofi Mensah", room: "1A" },
      { time: "09:00 - 10:00", subject: "Mathematics", teacher: "Mrs. Abena Osei", room: "1A" },
      { time: "10:15 - 11:15", subject: "Physical Education", teacher: "Mr. Samuel Aidoo", room: "Ground" },
      { time: "11:15 - 12:15", subject: "Arts", teacher: "Ms. Yaa Konadu", room: "Art Room" },
    ],
    Wednesday: [
      { time: "08:00 - 09:00", subject: "Science", teacher: "Ms. Ama Boateng", room: "Lab 1" },
      { time: "09:00 - 10:00", subject: "Mathematics", teacher: "Mrs. Abena Osei", room: "1A" },
      { time: "10:15 - 11:15", subject: "English", teacher: "Mr. Kofi Mensah", room: "1A" },
      { time: "11:15 - 12:15", subject: "Computer Studies", teacher: "Mr. Eric Okyere", room: "Computer Lab" },
    ],
    Thursday: [
      { time: "08:00 - 09:00", subject: "Social Studies", teacher: "Mr. Kwame Asante", room: "1A" },
      { time: "09:00 - 10:00", subject: "Science", teacher: "Ms. Ama Boateng", room: "Lab 1" },
      { time: "10:15 - 11:15", subject: "Mathematics", teacher: "Mrs. Abena Osei", room: "1A" },
      { time: "11:15 - 12:15", subject: "Music", teacher: "Ms. Adwoa Appiah", room: "Music Room" },
    ],
    Friday: [
      { time: "08:00 - 09:00", subject: "English", teacher: "Mr. Kofi Mensah", room: "1A" },
      { time: "09:00 - 10:00", subject: "Physical Education", teacher: "Mr. Samuel Aidoo", room: "Ground" },
      { time: "10:15 - 11:15", subject: "Science", teacher: "Ms. Ama Boateng", room: "Lab 1" },
      { time: "11:15 - 12:15", subject: "Assembly", teacher: "All Teachers", room: "Hall" },
    ],
  },
}
